# Generated by Django 5.2.8 on 2025-11-20 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='phoneNumber',
            field=models.CharField(default='+258 ', max_length=14, unique=True),
        ),
    ]
