# Generated by Django 5.2.8 on 2025-12-12 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_doctor_profile_patient_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='firstname',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='doctor',
            name='lastname',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='profile',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='patient',
            name='phoneNumber',
            field=models.CharField(default='+258 ', max_length=14, unique=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='profile',
            field=models.ImageField(blank=True, default='defaultpfp.jpg', null=True, upload_to=''),
        ),
    ]
