# Generated by Django 5.2.8 on 2025-11-07 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_users_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('m', 'Male'), ('f', 'Female')], default='', max_length=8),
        ),
        migrations.AddField(
            model_name='patient',
            name='phoneNumber',
            field=models.CharField(default='000000000', max_length=15, unique=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='residence',
            field=models.CharField(default='Unknown', max_length=50),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='user',
            field=models.OneToOneField(limit_choices_to={'role': 'doctor'}, on_delete=django.db.models.deletion.CASCADE, to='users.users'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='age',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='patient',
            name='user',
            field=models.OneToOneField(limit_choices_to={'role': 'patient '}, on_delete=django.db.models.deletion.CASCADE, to='users.users'),
        ),
        migrations.AlterField(
            model_name='users',
            name='role',
            field=models.CharField(choices=[('doctor', 'Doctor'), ('patient', 'Patient')], max_length=20),
        ),
    ]
