# Generated by Django 5.2.8 on 2025-11-07 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_doctor_name_patient_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='birthDate',
            field=models.DateField(default='1900-01-01'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='residence',
            field=models.CharField(default='', max_length=50),
        ),
    ]
