# Generated by Django 5.2.8 on 2025-11-07 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_patient_gender_patient_phonenumber_patient_residence_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='phoneNumber',
            field=models.CharField(default='(+258) ', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='user',
            field=models.OneToOneField(limit_choices_to={'role': 'patient'}, on_delete=django.db.models.deletion.CASCADE, to='users.users'),
        ),
    ]
