# Generated by Django 5.2.8 on 2025-11-11 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_doctor_birthdate_alter_patient_residence'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='available_days',
        ),
        migrations.AddField(
            model_name='doctor',
            name='role',
            field=models.CharField(default='doctor', max_length=8),
        ),
        migrations.AddField(
            model_name='patient',
            name='role',
            field=models.CharField(default='patient', max_length=8),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='name',
            field=models.CharField(default='Dr. ', max_length=255),
        ),
    ]
