# Generated by Django 5.2.8 on 2025-11-11 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_doctor_available_days_doctor_role_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='role',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='role',
        ),
        migrations.AddField(
            model_name='doctor',
            name='is_booked',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='is_booked',
            field=models.BooleanField(default=False),
        ),
    ]
