# Generated by Django 5.2.8 on 2025-11-07 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_patient_phonenumber_alter_patient_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='age',
            new_name='birthDate',
        ),
    ]
