# Generated by Django 5.2.8 on 2025-11-15 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_doctor_role_remove_patient_role_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='name',
            new_name='firstname',
        ),
        migrations.AddField(
            model_name='patient',
            name='lastname',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='birthDate',
            field=models.DateField(default='2000-01-01'),
        ),
    ]
