# Generated by Django 5.2.8 on 2025-12-14 21:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_doctor_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='phoneNumber',
            field=models.CharField(default='+258 ', max_length=13, unique=True, validators=[django.core.validators.RegexValidator(message='Invalid Phone Number!', regex='^\\+258(8[234567]|84|87|82|85|83)\\d{6}$')]),
        ),
        migrations.AlterField(
            model_name='patient',
            name='phoneNumber',
            field=models.CharField(default='+258 ', max_length=13, unique=True, validators=[django.core.validators.RegexValidator(message='Invalid Phone Number!', regex='^\\+258(8[234567]|84|87|82|85|83)\\d{6}$')]),
        ),
    ]
