# Generated by Django 5.2.8 on 2025-11-17 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_alter_appointment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='previous_status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
