# Generated by Django 5.2.8 on 2025-11-17 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_appointment_previous_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='previous_status',
        ),
    ]
